In [21]:
import pandas as pd

In [22]:
data = {'NOMBRE':['maria','julio','ana'], 'CARRERA': ['Ingeniería','Derecho','Médico']}

In [23]:
estudiantes = pd.DataFrame(data)
print(estudiantes)

  NOMBRE     CARRERA
0  maria  Ingeniería
1  julio     Derecho
2    ana      Médico


In [24]:
df = pd.DataFrame([['Maria',27],['Julio',23],['Ana',18]],columns=['Nombre','Edad'])
print(df)

  Nombre  Edad
0  Maria    27
1  Julio    23
2    Ana    18


# DataFrame a partir de un array

In [25]:
import numpy as np

df_ale = np.random.randn(4,3)
print(df_ale)


[[ 1.32793059 -0.94834225 -0.53830599]
 [-0.42605813  0.4957831  -0.12363729]
 [-0.0811221   0.08477854 -0.29152326]
 [ 0.82996772 -0.59477148 -0.689721  ]]


In [26]:
df = pd.DataFrame(df_ale, columns=['a','b','c'])
print(df)

          a         b         c
0  1.327931 -0.948342 -0.538306
1 -0.426058  0.495783 -0.123637
2 -0.081122  0.084779 -0.291523
3  0.829968 -0.594771 -0.689721
